# Use double quotes instead of single quotes when using line carriage (\n)
SignEditMessage: "&9%player%&f in %server% (%playerworld%) created a sign at %playerxyz%.\nSign text: %line1% %line2% %line3% %line4%"
ItemRenameMessage: "&9%player%&f in %server% (%playerworld%) named an item at %playerxyz%.\nItem Type: %type% Name: %name%"
BookEditMessage: "&9%player%&f in %server% (%playerworld%) wrote a book at %playerxyz%.\nThe book has been copied to the chest at %chestxyz% (%chestworld%)"

# Feedback messages
SignSpyOnMessage: '&7EventLogger notifications enabled.'
SignSpyOffMessage: '&7EventLogger notifications disabled.'
ReloadMessage: '&9The EventLogger configuration has been reloaded.'
MessageSentConfirmation: '&9Your message has been sent.'