name: EventLogger
main: me.jaime29010.eventlogger.bukkit.Main
version: ${project.version}
author: [jaime29010]
commands:
  signspy:
    description: 'Broadcast a message to moderators (only from console)'
    aliases: [ss, sb]